[supervisord]
nodaemon=true
logfile=/app/log/supervisord.log
pidfile=/app/run/supervisord.pid

[program:gunicorn]
command=/usr/local/bin/gunicorn -w 4 -b 0.0.0.0:8000 main:app
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/log/supervisor/gunicorn.log
stderr_logfile=/app/log/supervisor/gunicorn_error.log
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/app/log/supervisor/nginx.log
stderr_logfile=/app/log/supervisor/nginx_error.log
user=root